import { AlertTriangle, Crosshair, DatabaseZap, Focus, PanelRightClose, Route, ShieldAlert, X } from 'lucide-react';
import { CartesianGrid, Line, LineChart, ResponsiveContainer, Tooltip, XAxis, YAxis } from 'recharts';
import type { AnalysisEntity } from '../../types/analysis';
import { useTrackingStore } from '../../store/tracking';
import { useWorkspaceStore } from '../../store/workspace';
import { checkText } from '../../services/reports';
import { behaviorAtTime, clockSeconds, formatClock, movementAtTime, positionAtTime, reportsUntil } from '../../services/analysis-playback';
import { evidenceSentence, formatAttention, formatBehavior, formatEvidenceFlag, formatMovementState, formatReportSource, formatRiskLevel, formatUnavailable, formatVehicleClass, humanizeAssessmentText } from '../../services/formatters';
import { Button } from '../ui/button';
import { ReportVerdictBadge } from '../reports/ReportVerdictBadge';

const value = (number: number, digits = 1) => Number.isFinite(number) ? number.toFixed(digits) : formatUnavailable();
const meters = (number: number) => `${value(number, 1)} m`;
const speed = (number: number) => `${value(number, 2)} m/s`;
const degrees = (number: number) => `${value(number, 1)}°`;

function DetailSection({ title, meta, children }: { title: string; meta?: string; children: React.ReactNode }) {
  return <section className="entity-detail-section"><header><h2>{title}</h2>{meta && <span>{meta}</span>}</header>{children}</section>;
}

function EvidenceFlags({ flags, empty }: { flags: string[]; empty: string }) {
  return flags.length ? <><p className="entity-empty-note">{evidenceSentence(flags)}</p><div className="entity-flag-list">{flags.map(flag => <span key={flag}>{formatEvidenceFlag(flag)}</span>)}</div></> : <p className="entity-empty-note">{empty}</p>;
}

export function TrackDetail({ entity, playbackTime }: { entity: AnalysisEntity; playbackTime?: number }) {
  const select = useTrackingStore(state => state.selectTrack);
  const follow = useTrackingStore(state => state.followVehicle);
  const setFollow = useTrackingStore(state => state.setFollowVehicle);
  const requestView = useTrackingStore(state => state.requestView);
  const assessment = entity.risk.assessment;
  const time = playbackTime ?? clockSeconds(entity.last_seen);
  const position = positionAtTime(entity, time);
  const movement = movementAtTime(entity, time);
  const behavior = behaviorAtTime(entity, time);
  const visibleReports = reportsUntil(entity, time);
  const visibleMovementHistory = entity.movement_history.filter(item => clockSeconds(item.time) <= time);
  const visibleBehaviorHistory = entity.behavior_history.filter(item => clockSeconds(item.time) <= time);
  const observedTotal = Object.values(entity.vehicle_class.observed_classes).reduce((sum, count) => sum + (count ?? 0), 0);
  return <aside className="vehicle-details entity-track-detail" aria-label="Araç detayları">
    <div className="details-heading"><span className="section-eyebrow">TRACK DETAYI</span><span className="entity-detail-heading-actions"><Button variant="ghost" size="icon" aria-label="Detay panelini daralt" onClick={() => useWorkspaceStore.getState().toggleInspector()}><PanelRightClose size={15} /></Button><Button variant="ghost" size="icon" aria-label="Track seçimini temizle" onClick={() => select(null)}><X size={16} /></Button></span></div>
    <div className="entity-detail-title"><span><Route size={18} /></span><div><small>{formatClock(time)} ANINDAKİ DURUM</small><strong>{entity.track_id}</strong><em>{formatVehicleClass(entity.vehicle_class.canonical)}{position?.stale ? ' · son bilinen konum' : ''}</em></div><span className={`entity-risk risk-${(assessment?.risk_level ?? 'UNKNOWN').toLowerCase()}`}>{formatRiskLevel(assessment?.risk_level ?? 'UNKNOWN')}</span></div>
    <div className="vehicle-actions"><Button variant={follow ? 'default' : 'outline'} aria-pressed={follow} onClick={() => setFollow(!follow)}><Crosshair size={13} />Takip et</Button><Button variant="outline" onClick={() => requestView('vehicle')}><Focus size={13} />Haritada odaklan</Button></div>

    {!entity.vehicle_class.consistent && <div className="entity-quality-warning"><DatabaseZap size={16} /><span><strong>Araç sınıflandırması tutarsız</strong><small>Gözlemler araç sınıfı konusunda tam uyumlu değil. Bu bir veri kalitesi göstergesidir, tehdit sınıflandırması değildir.</small></span></div>}
    {entity.risk.error && <div className="entity-analysis-error" role="alert"><ShieldAlert size={16} /><span><strong>Risk analizi hatası</strong><small>{humanizeAssessmentText(entity.risk.error)}</small></span></div>}

    <DetailSection title="Kimlik" meta={`${entity.observation_count} gözlem`}><dl className="entity-detail-grid"><div><dt>Track kimliği</dt><dd>{entity.track_id}</dd></div><div><dt>İlk görülme</dt><dd>{entity.first_seen}</dd></div><div><dt>Son görülme</dt><dd>{entity.last_seen}</dd></div><div><dt>Ana araç sınıfı</dt><dd>{formatVehicleClass(entity.vehicle_class.canonical)}</dd></div><div><dt>Tespit güveni</dt><dd>{Math.round(entity.vehicle_class.average_detection_confidence * 100)}%</dd></div><div><dt>Sınıf tutarlı mı?</dt><dd>{entity.vehicle_class.consistent ? 'Evet' : 'Hayır'}</dd></div></dl>
      <div className="observed-classes"><span>GÖZLENEN ARAÇ SINIFLARI</span>{Object.entries(entity.vehicle_class.observed_classes).map(([name, count]) => { const percentage = observedTotal ? (count ?? 0) / observedTotal * 100 : 0; return <div key={name}><label><span>{formatVehicleClass(name)}</span><b>{count}</b></label><i><em style={{ width: `${percentage}%` }} /></i></div>; })}</div>
    </DetailSection>

    <DetailSection title="Konum" meta={position ? `${position.zone} · ${formatClock(time)}` : 'Henüz gözlenmedi'}>{position ? <dl className="entity-detail-grid"><div><dt>Enlem</dt><dd>{value(position.lat, 6)}</dd></div><div><dt>Boylam</dt><dd>{value(position.lon, 6)}</dd></div><div><dt>Üsse mesafe</dt><dd>{meters(position.distance_to_base_m)}</dd></div><div><dt>Üsse en düşük mesafe</dt><dd>{meters(entity.minimum_distance_to_base_m)}</dd></div></dl> : <p className="entity-empty-note">Bu track {formatClock(time)} anında henüz başlamamış.</p>}</DetailSection>

    <DetailSection title="Hareket" meta={movement ? `${formatMovementState(movement.state)} · ${movement.time}` : formatUnavailable()}>{movement ? <dl className="entity-detail-grid"><div><dt>Hareket durumu</dt><dd>{formatMovementState(movement.state)}</dd></div><div><dt>Hız</dt><dd>{speed(movement.speed_mps)}</dd></div><div><dt>Üsse yaklaşma hızı</dt><dd>{speed(movement.closing_speed_mps)}</dd></div><div><dt>Tahmini varış</dt><dd>{movement.eta_min == null ? formatUnavailable() : `${value(movement.eta_min)} dk`}</dd></div><div><dt>Üsse mesafe</dt><dd>{meters(movement.distance_to_base_m)}</dd></div><div><dt>Yön</dt><dd>{formatUnavailable()}</dd></div><div><dt>Üs yönü</dt><dd>{formatUnavailable()}</dd></div><div><dt>Hareket ediyor mu?</dt><dd>{formatUnavailable()}</dd></div></dl> : <p className="entity-empty-note">{formatClock(time)} anına kadar hareket durumu yok.</p>}</DetailSection>

    <DetailSection title="Davranış Analizi" meta={behavior ? `${formatBehavior(behavior.behavior)} · ${behavior.time}` : formatUnavailable()}>{behavior ? <><dl className="entity-detail-grid"><div><dt>Davranış</dt><dd>{formatBehavior(behavior.behavior)}</dd></div><div><dt>Rota verimliliği</dt><dd>{value(behavior.path_efficiency, 3)}</dd></div><div><dt>Yön değişimi</dt><dd>{degrees(behavior.heading_change_total_deg)}</dd></div><div><dt>Rota uzunluğu</dt><dd>{formatUnavailable()}</dd></div><div><dt>Net yer değiştirme</dt><dd>{formatUnavailable()}</dd></div><div><dt>Yayılım</dt><dd>{formatUnavailable()}</dd></div></dl><EvidenceFlags flags={behavior.flags} empty="Bu anda davranış göstergesi yok." /></> : <p className="entity-empty-note">{formatClock(time)} anına kadar davranış analizi yok.</p>}</DetailSection>

    <DetailSection title="Risk Değerlendirmesi" meta={assessment ? `Genel / son analiz · ${formatAttention(assessment.recommended_attention)}` : formatRiskLevel('UNKNOWN')}>{assessment ? <><p className="field-report-disclaimer"><AlertTriangle size={12} />Risk değerlendirmesi backend tarafından üretilen genel/son LLM çıktısıdır; {formatClock(time)} için yeniden hesaplanmaz.</p><div className="risk-assessment-head"><span className={`entity-risk risk-${assessment.risk_level.toLowerCase()}`}>{formatRiskLevel(assessment.risk_level)}</span><span className={`entity-attention attention-${assessment.recommended_attention.toLowerCase()}`}>{formatAttention(assessment.recommended_attention)}</span><b>%{Math.round(assessment.confidence * 100)} değerlendirme güveni</b></div><p className="risk-assessment-summary">{humanizeAssessmentText(assessment.summary)}</p><div className="assessment-list"><h3>Değerlendirme gerekçeleri</h3>{assessment.reasoning.map((item, index) => <p key={`${index}-${item}`}>{humanizeAssessmentText(item)}</p>)}</div><div className="assessment-list evidence"><h3>Temel bulgular</h3>{assessment.key_evidence.map(item => <p key={item}>{humanizeAssessmentText(item)}</p>)}</div><div className="assessment-list uncertainty"><h3>Belirsizlikler</h3>{assessment.uncertainties.map(item => <p key={item}>{humanizeAssessmentText(item)}</p>)}</div></> : <div className="unknown-assessment"><ShieldAlert size={17} /><span><strong>{formatRiskLevel('UNKNOWN')}</strong><small>Backend risk değerlendirmesi mevcut değil.</small></span></div>}</DetailSection>

    <DetailSection title="Kanıt Göstergeleri"><p className="field-report-disclaimer"><AlertTriangle size={12} />Kanıt göstergeleri backend’in güncel ve geçmiş özetleridir; playback sırasında her saniye için yeniden hesaplanmaz.</p><div className="evidence-groups"><div><h3>Güncel kanıt göstergeleri</h3><EvidenceFlags flags={entity.current_evidence_flags} empty="Güncel kanıt göstergesi yok." /></div><div><h3>Geçmiş kanıt göstergeleri</h3><EvidenceFlags flags={entity.historical_evidence_flags} empty="Geçmiş kanıt göstergesi yok." /></div></div></DetailSection>

    <DetailSection title="Saha Raporları" meta={`${visibleReports.length}/${entity.reports.length} rapor · ${formatClock(time)} anına kadar`}><p className="field-report-disclaimer"><AlertTriangle size={12} />Saha raporları destekleyici bilgidir; tek başına kesin doğruluk kaynağı olarak ele alınmaz.</p>{visibleReports.length ? <div className="entity-report-list">{visibleReports.map((report, index) => <article key={`${report.time}-${index}`}><header><span><strong>{report.time}</strong><small>{formatReportSource(report.source)}</small></span><ReportVerdictBadge verdict={report.verdict} /></header><p>{humanizeAssessmentText(report.text)}</p><dl><div><dt>Eşleşme mesafesi</dt><dd>{meters(report.match_distance_m)}</dd></div><div><dt>Desteklenen kontrol</dt><dd>{report.supported_checks}</dd></div><div><dt>Çelişen kontrol</dt><dd>{report.contradicted_checks}</dd></div></dl>{report.reasons.length > 0 && <div className="report-reasons">{report.reasons.map(reason => <span key={reason}>{humanizeAssessmentText(reason)}</span>)}</div>}<details><summary>Kanıt kontrolleri ({report.checks.length})</summary>{report.checks.map((check, checkIndex) => <div className="entity-report-check" key={`${check.claim}-${checkIndex}`}><span>{humanizeAssessmentText(check.claim)}</span><b>{formatEvidenceFlag(check.result)}</b><small>{humanizeAssessmentText(checkText(check.value))}</small></div>)}</details></article>)}</div> : <p className="entity-empty-note">{formatClock(time)} anına kadar görünen saha raporu yok.</p>}</DetailSection>

    <DetailSection title="Hareket Geçmişi" meta={`${visibleMovementHistory.length}/${entity.movement_history.length} nokta`}><div className="entity-history-chart" aria-label="Zamana göre üs mesafesi"><div className="chart-heading"><h3>Zamana göre üs mesafesi</h3><span>metre</span></div><ResponsiveContainer width="100%" height="100%"><LineChart data={visibleMovementHistory} margin={{ top: 8, right: 8, bottom: 0, left: -18 }}><CartesianGrid vertical={false} stroke="#293940" strokeDasharray="2 4" /><XAxis dataKey="time" tick={{ fill: '#81949d', fontSize: 7 }} axisLine={false} tickLine={false} /><YAxis dataKey="distance_to_base_m" tick={{ fill: '#81949d', fontSize: 7 }} axisLine={false} tickLine={false} /><Tooltip contentStyle={{ background: '#142027', border: '1px solid #3c4f58', borderRadius: 4, fontSize: 8 }} formatter={entry => [`${Number(entry).toFixed(1)} m`, 'Üs mesafesi']} /><Line type="monotone" dataKey="distance_to_base_m" stroke="#85baa6" strokeWidth={2} dot={{ r: 2, fill: '#a5d8c3' }} isAnimationActive={false} /></LineChart></ResponsiveContainer></div>
      <div className="entity-history-table"><table><thead><tr><th>Zaman</th><th>Durum</th><th>Mesafe</th><th>Hız</th><th>Yaklaşma</th><th>Tahmini varış</th></tr></thead><tbody>{visibleMovementHistory.map(item => <tr key={item.time}><td>{item.time}</td><td>{formatMovementState(item.state)}</td><td>{meters(item.distance_to_base_m)}</td><td>{speed(item.speed_mps)}</td><td>{speed(item.closing_speed_mps)}</td><td>{item.eta_min == null ? formatUnavailable() : `${value(item.eta_min)} dk`}</td></tr>)}</tbody></table></div>
    </DetailSection>

    <DetailSection title="Davranış Geçmişi" meta={`${visibleBehaviorHistory.length}/${entity.behavior_history.length} değişim`}><div className="behavior-history-list">{visibleBehaviorHistory.length ? visibleBehaviorHistory.map((item, index) => <div key={`${item.time}-${index}`}><i className={`behavior-dot behavior-${item.behavior.toLowerCase()}`} /><span><strong>{formatBehavior(item.behavior)}</strong><small>{item.time} · rota verimliliği {value(item.path_efficiency, 3)} · yön değişimi {degrees(item.heading_change_total_deg)}</small><EvidenceFlags flags={item.flags} empty="Gösterge yok" /></span></div>) : <p className="entity-empty-note">{formatClock(time)} anına kadar davranış geçmişi yok.</p>}</div></DetailSection>
  </aside>;
}
