import { test, expect } from '@playwright/test';
test('renders all data, supports selection and fits on mobile', async ({ page }, testInfo) => {
  const errors: string[] = [];
  page.on('pageerror', error => errors.push(error.message));
  page.on('console', message => { if (message.text().startsWith('Map resource error:')) errors.push(message.text()); });
  await page.goto('/');
  await expect(page.locator('.vehicle-marker')).toHaveCount(16);
  await expect(page.locator('.zone-marker')).toHaveCount(8);
  await expect(page.locator('.base-marker')).toHaveCount(1);
  await page.getByRole('button', { name: 'Select vehicle T0001', exact: true }).click();
  await expect(page.locator('.detail-title')).toContainText('T0001');
  await expect(page.locator('.vehicle-details')).toContainText('39.950586');
  await expect(page.locator('.vehicle-marker.selected')).toHaveCount(1);
  await page.getByRole('button', { name: 'Clear vehicle selection' }).click();
  await expect(page.locator('.vehicle-marker.selected')).toHaveCount(0);
  await page.getByRole('textbox', { name: 'Search vehicle tracks' }).fill('T0002');
  await expect(page.locator('.track-row')).toHaveCount(1);
  await page.locator('.track-row').click();
  await expect(page.locator('.detail-title')).toContainText('T0002');
  await page.getByRole('button', { name: 'Fit all tracks' }).click();
  const slider = page.getByRole('slider', { name: 'Simulated time', exact: true });
  const min = Number(await slider.getAttribute('min')), max = Number(await slider.getAttribute('max'));
  const marker = page.getByRole('button', { name: 'Select vehicle T0002', exact: true });
  await expect(marker).toHaveCSS('position', 'absolute');
  const originalTransform = await marker.evaluate(element => element.style.transform);
  await slider.fill(String((min + max) / 2));
  await expect.poll(() => marker.evaluate(element => element.style.transform)).not.toBe(originalTransform);
  await expect(page.locator('.vehicle-details')).toContainText('PREVIOUS KNOWN POINT');
  await page.getByRole('combobox', { name: 'Playback speed' }).selectOption('60');
  await page.getByRole('button', { name: 'Play', exact: true }).click();
  await expect.poll(async () => Number(await slider.inputValue())).toBeGreaterThan((min + max) / 2 + 10);
  await expect(marker).toHaveAttribute('aria-pressed', 'true');
  await page.getByRole('button', { name: 'Pause', exact: true }).click();
  const pausedTime = await slider.inputValue();
  await page.waitForTimeout(150);
  expect(await slider.inputValue()).toBe(pausedTime);
  await page.getByRole('tab', { name: 'Layers', exact: true }).click();
  await page.getByRole('checkbox', { name: 'Vehicle markers' }).uncheck();
  await expect(marker).toBeHidden();
  await page.getByRole('checkbox', { name: 'Vehicle markers' }).check();
  await expect(marker).toBeVisible();
  await page.getByRole('checkbox', { name: 'Zones', exact: true }).uncheck();
  await expect(page.locator('.zone-marker').first()).toBeHidden();
  await page.getByRole('checkbox', { name: 'Zones', exact: true }).check();
  await page.getByRole('checkbox', { name: 'Base', exact: true }).uncheck();
  await expect(page.locator('.base-marker')).toBeHidden();
  await page.getByRole('checkbox', { name: 'Base', exact: true }).check();
  await slider.fill(String(max - 1));
  await page.getByRole('button', { name: 'Play', exact: true }).click();
  await expect(page.getByRole('button', { name: 'Play', exact: true })).toBeVisible();
  expect(Number(await slider.inputValue())).toBe(max);
  await page.getByRole('button', { name: 'Jump to beginning' }).click();
  expect(Number(await slider.inputValue())).toBe(min);
  await slider.fill(String((min + max) / 2));
  await page.screenshot({ path: testInfo.outputPath('atlas-desktop.png') });
  await page.setViewportSize({ width: 390, height: 844 });
  await expect(page.locator('.map-canvas')).toBeVisible();
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBe(true);
  await page.screenshot({ path: testInfo.outputPath('atlas-mobile.png'), fullPage: true });
  expect(errors).toEqual([]);
});

test('selected vehicle metrics, charts, history and follow actions', async ({ page }, testInfo) => {
  const errors: string[] = [];
  page.on('pageerror', error => errors.push(error.message));
  await page.goto('/');
  await expect(page.getByText('Inspect a vehicle', { exact: true })).toBeVisible();
  await expect(page.locator('.vehicle-marker')).toHaveCount(16);
  await page.getByRole('textbox', { name: 'Search vehicle tracks' }).fill('T0002');
  await page.locator('.track-row').click();
  const panel = page.getByRole('complementary', { name: 'Vehicle details' });
  await expect(panel).toContainText('DISTANCE TO BASE');
  await expect(panel).toContainText('DISTANCE TRAVELED');
  await expect(panel.locator('.recharts-surface')).toHaveCount(2);
  const slider = page.getByRole('slider', { name: 'Simulated time', exact: true });
  const min = Number(await slider.getAttribute('min')), max = Number(await slider.getAttribute('max'));
  await slider.fill(String((min + max) / 2));
  await expect(panel.locator('tbody tr')).toHaveCount(5);
  const follow = page.getByRole('button', { name: 'Follow', exact: true });
  await follow.click();
  await expect(follow).toHaveAttribute('aria-pressed', 'true');
  const marker = page.getByRole('button', { name: 'Select vehicle T0002', exact: true });
  const centered = async () => {
    const m = await marker.boundingBox(), canvas = await page.locator('.map-canvas').boundingBox();
    return m && canvas ? Math.hypot(m.x + m.width / 2 - canvas.x - canvas.width / 2, m.y + m.height / 2 - canvas.y - canvas.height / 2) : Infinity;
  };
  await expect.poll(centered).toBeLessThan(3);
  await page.getByRole('combobox', { name: 'Playback speed' }).selectOption('60');
  await page.getByRole('button', { name: 'Play', exact: true }).click();
  await expect.poll(async () => Number(await slider.inputValue())).toBeGreaterThan((min + max) / 2 + 20);
  await expect.poll(centered).toBeLessThan(3);
  await page.getByRole('button', { name: 'Pause', exact: true }).click();
  await page.getByRole('button', { name: 'Focus on route', exact: true }).click();
  await expect(follow).toHaveAttribute('aria-pressed', 'false');
  await follow.click();
  await page.getByRole('button', { name: 'Reset view', exact: true }).click();
  await expect(follow).toHaveAttribute('aria-pressed', 'false');
  await panel.evaluate(element => { element.scrollTop = 0; });
  await page.screenshot({ path: testInfo.outputPath('atlas-inspector.png') });
  await page.getByRole('button', { name: 'Clear vehicle selection' }).click();
  await expect(page.getByText('Inspect a vehicle', { exact: true })).toBeVisible();
  expect(errors).toEqual([]);
});

test('search and filters synchronize map, list, zones and map tools', async ({ page }, testInfo) => {
  await page.goto('/');
  await expect(page.locator('.vehicle-marker:visible')).toHaveCount(16);
  const search = page.getByRole('textbox', { name: 'Search vehicle tracks' });
  await search.fill('t0002');
  await expect(page.locator('.track-row')).toHaveCount(1);
  await expect(page.locator('.vehicle-marker:visible')).toHaveCount(1);
  await page.locator('.track-row').click();
  const marker = page.getByRole('button', { name: 'Select vehicle T0002', exact: true });
  // Let the short camera focus transition finish before positioning the pointer.
  await page.waitForTimeout(450);
  await marker.hover();
  await expect(page.locator('.vehicle-tooltip')).toContainText('km/h');
  await expect(page.locator('.vehicle-tooltip')).toContainText('km to base');
  await page.getByRole('tab', { name: 'Filters', exact: true }).click();
  await page.getByRole('spinbutton', { name: 'Minimum speed' }).fill('9999');
  await expect(page.locator('.vehicle-marker:visible')).toHaveCount(0);
  await expect(page.locator('.detail-title')).toContainText('T0002');
  await page.getByRole('button', { name: 'Clear all filters', exact: true }).click();
  await expect(page.locator('.vehicle-marker:visible')).toHaveCount(16);
  await expect(search).toHaveValue('');
  await page.getByRole('tab', { name: 'Zones', exact: true }).click();
  await page.getByRole('button', { name: 'Focus zone Kuzey Yolu', exact: true }).click();
  await page.getByRole('button', { name: 'Filter near Kuzey Yolu', exact: true }).click();
  await expect.poll(() => page.locator('.vehicle-marker:visible').count()).toBeLessThan(16);
  await page.getByRole('tab', { name: 'Vehicles', exact: true }).click();
  expect(await page.locator('.track-row').count()).toBe(await page.locator('.vehicle-marker:visible').count());
  await page.getByRole('button', { name: 'Toggle sidebar' }).click();
  await expect(page.getByRole('complementary', { name: 'Operations controls' })).toHaveCount(0);
  await page.getByRole('button', { name: 'Toggle sidebar' }).click();
  await expect(page.getByRole('complementary', { name: 'Operations controls' })).toBeVisible();
  await page.getByRole('button', { name: 'Clear', exact: true }).click();
  await page.getByRole('button', { name: 'Fit selected vehicle', exact: true }).click();
  await page.getByRole('button', { name: 'Reset map view', exact: true }).click();
  await page.getByRole('tab', { name: 'Layers', exact: true }).click();
  await page.getByRole('checkbox', { name: 'Traveled route', exact: true }).uncheck();
  await page.getByRole('checkbox', { name: 'Future route', exact: true }).uncheck();
  await expect(page.locator('.vehicle-marker:visible')).toHaveCount(16);
  await page.getByRole('checkbox', { name: 'Traveled route', exact: true }).check();
  await page.getByRole('checkbox', { name: 'Future route', exact: true }).check();
  const full = page.getByRole('button', { name: 'Fullscreen map', exact: true });
  if (await full.isEnabled()) { await full.click(); await expect(page.getByRole('button', { name: 'Exit fullscreen map', exact: true })).toBeVisible(); await page.getByRole('button', { name: 'Exit fullscreen map', exact: true }).click(); }
  await page.getByRole('tab', { name: 'Vehicles', exact: true }).click();
  await page.screenshot({ path: testInfo.outputPath('atlas-explorer.png') });
});
